development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rajin_belajar_development
  pool: 5

staging:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: <%= ENV['POSTGRESQL_DATABASE'] %>
  pool: 5 
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rajin_belajar_development
  pool: 5 
  username: postgres
  password: postgres