development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rajin_belajar_development
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: rajin_belajar_development
  pool: 5 
  username: postgres
  password: postgres